# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a2aad476cf47b07800ccaaf3323ff4c58086b301398b07a353bb9d2251f997b1d2d1685dfc00b96239e24128889fa63c904a336237cbac1acb31a0c055a619b

test:
  secret_key_base: 134f3c1f949e19b2705a2cd2f8fc55d0b70bd8093afda79149c67a2ba7c52b3b4d2a563560403243d2424deaef7bba4936461bcc3b46822708fb816c7c759f5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
